-- begin SALES_ORDER
alter table SALES_ORDER add constraint FK_SALES_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references SALES_CUSTOMER(ID)^
alter table SALES_ORDER add constraint FK_SALES_ORDER_ON_SHOP foreign key (SHOP_ID) references SALES_SHOP(ID)^
alter table SALES_ORDER add constraint FK_SALES_ORDER_ON_ORDER_LINE_LIST foreign key (ORDER_LINE_LIST_ID) references SALES_ORDER_LINE(ID)^
create index IDX_SALES_ORDER_ON_CUSTOMER on SALES_ORDER (CUSTOMER_ID)^
create index IDX_SALES_ORDER_ON_SHOP on SALES_ORDER (SHOP_ID)^
create index IDX_SALES_ORDER_ON_ORDER_LINE_LIST on SALES_ORDER (ORDER_LINE_LIST_ID)^
-- end SALES_ORDER
-- begin SALES_PRODUCT
create unique index IDX_SALES_PRODUCT_UNQ on SALES_PRODUCT (NAME, PRICE) ^
-- end SALES_PRODUCT
-- begin SALES_ORDER_LINE
alter table SALES_ORDER_LINE add constraint FK_SALES_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references SALES_PRODUCT(ID)^
create index IDX_SALES_ORDER_LINE_ON_PRODUCT on SALES_ORDER_LINE (PRODUCT_ID)^
-- end SALES_ORDER_LINE
-- begin SALES_SHOP_PRODUCT_LINK
alter table SALES_SHOP_PRODUCT_LINK add constraint FK_SHOPRO_ON_SHOP foreign key (SHOP_ID) references SALES_SHOP(ID)^
alter table SALES_SHOP_PRODUCT_LINK add constraint FK_SHOPRO_ON_PRODUCT foreign key (PRODUCT_ID) references SALES_PRODUCT(ID)^
-- end SALES_SHOP_PRODUCT_LINK
