alter table SALES_ORDER add constraint FK_SALES_ORDER_ON_ORDER_LINE_LIST foreign key (ORDER_LINE_LIST_ID) references SALES_ORDER_LINE(ID);
create index IDX_SALES_ORDER_ON_ORDER_LINE_LIST on SALES_ORDER (ORDER_LINE_LIST_ID);
